import type { Metadata } from "next";
import "@/app/globals.css";
import localFont from "next/font/local";
import { Inter_Tight } from "next/font/google";
import React from "react";

import Footer from "@/components/footer/Footer";
import NavBar from "@/components/nav/NavBar";

export const metadata: Metadata = {
  title: "Ophelix",
  description: "Generated by create next app",
};

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  display: "swap",
  subsets: ["latin"],
});

const ppEditorialNew = localFont({
  variable: "--font-pp-editorial",
  display: "swap",
  src: [
    {
      path: "../../public/fonts/pp-editorial-new/PPEditorialNew-Ultralight.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/pp-editorial-new/PPEditorialNew-UltralightItalic.otf",
      weight: "200",
      style: "italic",
    },
    {
      path: "../../public/fonts/pp-editorial-new/PPEditorialNew-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/pp-editorial-new/PPEditorialNew-Italic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/pp-editorial-new/PPEditorialNew-Ultrabold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/pp-editorial-new/PPEditorialNew-UltraboldItalic.otf",
      weight: "800",
      style: "italic",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${ppEditorialNew.variable} ${interTight.variable}`}
    >
      <body className="min-h-dvh antialiased">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
