import type { Metadata } from "next";
import "@/app/globals.css";
import { Inter_Tight, Playfair_Display } from "next/font/google";
import React from "react";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity/visual-editing";
import { DisableDraftMode } from "@/components/disableDraftMode";

import Footer from "@/components/footer/Footer";
import NavBar from "@/components/nav/NavBar";
import { SanityLive } from "@/sanity/lib/live";

export const metadata: Metadata = {
  title: "Ophelix",
  description: "Generated by create next app",
};

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  display: "swap",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  display: "swap",
  subsets: ["latin"]

});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${playfairDisplay.variable} ${interTight.variable}`}
    >
      <body className="min-h-dvh antialiased">
        <SanityLive />
        {(await draftMode()).isEnabled && (
          <>
            <DisableDraftMode />
            <VisualEditing />
          </>
        )}
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
