import type { Metadata } from "next";
import "./globals.css";

import NavBar from "@/components/nav/NavBar";
import AnnouncementBar from "@/components/announcementBar/AnnouncementBar";

export const metadata: Metadata = {
  title: "Ophelix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased w-screen`}>
        <AnnouncementBar />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
