/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Carousel = {
  _id: string;
  _type: "carousel";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline: string;
  headlineSubText?: string;
  carouselImages?: Array<
    {
      _key: string;
    } & ImageAsset
  >;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  rating?: number;
  testimonialText: string;
  name: string;
  occupation?: string;
  location: string;
};

export type UserStorySection = {
  _id: string;
  _type: "userStorySection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  subtext?: string;
  headlineImage: ImageAsset;
  storyBlocks?: Array<
    {
      _key: string;
    } & UserStoryInstance
  >;
};

export type MarketingPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "marketingPage";
};

export type NavigationHeaderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "navigationHeader";
};

export type FooterReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "footer";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landingPage?: MarketingPageReference;
  navbar?: NavigationHeaderReference;
  footer?: FooterReference;
};

export type CompanyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "company";
};

export type NavigationHeader = {
  _id: string;
  _type: "navigationHeader";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: CompanyReference;
  navigationLinks?: Array<
    {
      _key: string;
    } & Navigation
  >;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyDetails: CompanyReference;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Company = {
  _id: string;
  _type: "company";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  yearEstablished: string;
  address: Address;
  phone?: string;
  socialMediaLinks?: Array<
    {
      _key: string;
    } & SocialMedia
  >;
  logos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "logoImage";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Address = {
  _type: "address";
  streetName: string;
  streetNumber: string;
  postCode: string;
};

export type MarketingPage = {
  _id: string;
  _type: "marketingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug: Slug;
  publishedAt?: string;
  updatedAt?: string;
  pageSections: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & CtaSection)
    | ({
        _key: string;
      } & SplitSection)
    | {
        title: string;
        subtext?: string;
        headlineImage: ImageAsset;
        storyBlocks?: Array<
          {
            _key: string;
          } & UserStoryInstance
        >;
        _type: "userStorySection";
        _key: string;
      }
    | ({
        _key: string;
      } & TestimonialsSection)
    | ({
        _key: string;
      } & ImageAsset)
    | {
        headline: string;
        headlineSubText?: string;
        carouselImages?: Array<
          {
            _key: string;
          } & ImageAsset
        >;
        _type: "carousel";
        _key: string;
      }
  >;
};

export type ImageAsset = {
  _type: "imageAsset";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: string;
  caption?: string;
  attribution?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type TestimonialsSection = {
  _type: "testimonialsSection";
  title?: string;
  subtext?: string;
  testimonialList: Array<{
    rating?: number;
    testimonialText: string;
    name: string;
    occupation?: string;
    location: string;
    _type: "testimonial";
    _key: string;
  }>;
};

export type CtaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "cta";
};

export type CtaSection = {
  _type: "ctaSection";
  content: CtaReference;
  contentAlignment: Alignment;
  theme: "primary" | "background" | "dark";
};

export type Alignment = {
  _type: "alignment";
  alignmentType: "left" | "right" | "center";
};

export type SplitSection = {
  _type: "splitSection";
  content: CtaReference;
  layout?: "image-left" | "image-right";
  intent: "primary" | "muted" | "dark" | "neutral" | "white";
};

export type UserStoryInstance = {
  _type: "userStoryInstance";
  storyText: string;
  userStoryImage: ImageAsset;
};

export type Cta = {
  _id: string;
  _type: "cta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  eyebrow?: string;
  text?: string;
  ctaImage: ImageAsset;
  ctaNavigation1?: Navigation;
  ctaNavigation2?: Navigation;
  supportingNote?: string;
};

export type Navigation = {
  _type: "navigation";
  title?: string;
  type?: "internal" | "external";
  internalLink?: string;
  link?: string;
};

export type HeroReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "hero";
};

export type HeroSection = {
  _type: "heroSection";
  hero: HeroReference;
  alignment?: Alignment;
};

export type Hero = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  heroText?: string;
  heroImage?: ImageAsset;
  muxVideo?: MuxVideo;
  heroNavigation1?: Navigation;
  heroNavigation2?: Navigation;
};

export type MuxVideoAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mux.videoAsset";
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: MuxVideoAssetReference;
};

export type RichText = {
  _type: "richText";
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SocialMedia = {
  _type: "socialMedia";
  socialMediaTitle: string;
  socialMediaLink: string;
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<
    {
      _key: string;
    } & MuxTrack
  >;
  playback_ids?: Array<
    {
      _key: string;
    } & MuxPlaybackId
  >;
  static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<
    {
      _key: string;
    } & MuxStaticRenditionFile
  >;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  name?: string;
  ext?: string;
  height?: number;
  width?: number;
  bitrate?: number;
  filesize?: string;
  type?: string;
  status?: string;
  resolution_tier?: string;
  resolution?: string;
  id?: string;
  passthrough?: string;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
  language_code?: string;
  name?: string;
  status?: string;
  text_source?: string;
  text_type?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Carousel
  | Testimonial
  | UserStorySection
  | MarketingPageReference
  | NavigationHeaderReference
  | FooterReference
  | SiteSettings
  | CompanyReference
  | NavigationHeader
  | Footer
  | SanityImageAssetReference
  | Company
  | SanityImageCrop
  | SanityImageHotspot
  | Address
  | MarketingPage
  | ImageAsset
  | Slug
  | TestimonialsSection
  | CtaReference
  | CtaSection
  | Alignment
  | SplitSection
  | UserStoryInstance
  | Cta
  | Navigation
  | HeroReference
  | HeroSection
  | Hero
  | MuxVideoAssetReference
  | MuxVideo
  | RichText
  | SocialMedia
  | MuxVideoAsset
  | MuxAssetData
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries/landingPage.ts
// Variable: landingPageQuery
// Query: *[_type == "siteSettings"][0]{  "pageSections": landingPage->pageSections[]{    _type,    _key,    _type == "heroSection" => {      "title": hero->title,      "text": hero->heroText,      "heroNavigation1": hero->heroNavigation1,      "heroNavigation2": hero->heroNavigation2,      "muxVideo": hero->muxVideo {        "playbackId":asset->playbackId,      },      "heroImage": hero->heroImage    },    _type == "splitSection" => {      "eyebrow": content->eyebrow,      "title": content->title,      "ctaText": content->text,      "ctaImage": content->ctaImage,      "ctaNavigation1": content->ctaNavigation1,      "ctaNavigation2": content->ctaNavigation2,      layout,       intent    }, _type == "imageAsset" => {  ...,  image},  _type == "userStorySection" => {    ...  },   _type == "carousel" => {    ...  },   _type == "testimonialsSection" => {    ...  },   _type == "ctaSection" => {    "alignment":contentAlignment.alignmentType,    theme,    "ctaImage": content -> ctaImage,    "ctaNavigation1": content -> ctaNavigation1,     "ctaNavigation2": content->ctaNavigation2,     "ctaText": content->text,     "ctaTitle": content->title,  }  }  }
export type LandingPageQueryResult = {
  pageSections: Array<
    | {
        _type: "carousel";
        _key: string;
        headline: string;
        headlineSubText?: string;
        carouselImages?: Array<
          {
            _key: string;
          } & ImageAsset
        >;
      }
    | {
        _type: "ctaSection";
        _key: string;
        alignment: "center" | "left" | "right";
        theme: "background" | "dark" | "primary";
        ctaImage: ImageAsset;
        ctaNavigation1: Navigation | null;
        ctaNavigation2: Navigation | null;
        ctaText: string | null;
        ctaTitle: string;
      }
    | {
        _type: "heroSection";
        _key: string;
        title: string;
        text: string | null;
        heroNavigation1: Navigation | null;
        heroNavigation2: Navigation | null;
        muxVideo: {
          playbackId: string | null;
        } | null;
        heroImage: ImageAsset | null;
      }
    | {
        _type: "imageAsset";
        _key: string;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt: string;
        caption?: string;
        attribution?: string;
      }
    | {
        _type: "splitSection";
        _key: string;
        eyebrow: string | null;
        title: string;
        ctaText: string | null;
        ctaImage: ImageAsset;
        ctaNavigation1: Navigation | null;
        ctaNavigation2: Navigation | null;
        layout: "image-left" | "image-right" | null;
        intent: "dark" | "muted" | "neutral" | "primary" | "white";
      }
    | {
        _type: "testimonialsSection";
        _key: string;
        title?: string;
        subtext?: string;
        testimonialList: Array<{
          rating?: number;
          testimonialText: string;
          name: string;
          occupation?: string;
          location: string;
          _type: "testimonial";
          _key: string;
        }>;
      }
    | {
        _type: "userStorySection";
        _key: string;
        title: string;
        subtext?: string;
        headlineImage: ImageAsset;
        storyBlocks?: Array<
          {
            _key: string;
          } & UserStoryInstance
        >;
      }
  > | null;
} | null;

// Source: sanity/lib/queries/marketingPage.ts
// Variable: marketingPageQuery
// Query: *[_type == "marketingPage" && slug.current == $slug][0] {    "pageSections": pageSections[]       {    _type,    _key,    _type == "heroSection" => {      "title": hero->title,      "text": hero->heroText,      "heroNavigation1": hero->heroNavigation1,      "heroNavigation2": hero->heroNavigation2,      "muxVideo": hero->muxVideo {        "playbackId":asset->playbackId,      },      "heroImage": hero->heroImage    },    _type == "splitSection" => {      "eyebrow": content->eyebrow,      "title": content->title,      "ctaText": content->text,      "ctaImage": content->ctaImage,      "ctaNavigation1": content->ctaNavigation1,      "ctaNavigation2": content->ctaNavigation2,      layout,       intent    }, _type == "imageAsset" => {  ...,  image},  _type == "userStorySection" => {    ...  },   _type == "carousel" => {    ...  },   _type == "testimonialsSection" => {    ...  },   _type == "ctaSection" => {    "alignment":contentAlignment.alignmentType,    theme,    "ctaImage": content -> ctaImage,    "ctaNavigation1": content -> ctaNavigation1,     "ctaNavigation2": content->ctaNavigation2,     "ctaText": content->text,     "ctaTitle": content->title,  }  }   }
export type MarketingPageQueryResult = {
  pageSections: Array<
    | {
        _type: "carousel";
        _key: string;
        headline: string;
        headlineSubText?: string;
        carouselImages?: Array<
          {
            _key: string;
          } & ImageAsset
        >;
      }
    | {
        _type: "ctaSection";
        _key: string;
        alignment: "center" | "left" | "right";
        theme: "background" | "dark" | "primary";
        ctaImage: ImageAsset;
        ctaNavigation1: Navigation | null;
        ctaNavigation2: Navigation | null;
        ctaText: string | null;
        ctaTitle: string;
      }
    | {
        _type: "heroSection";
        _key: string;
        title: string;
        text: string | null;
        heroNavigation1: Navigation | null;
        heroNavigation2: Navigation | null;
        muxVideo: {
          playbackId: string | null;
        } | null;
        heroImage: ImageAsset | null;
      }
    | {
        _type: "imageAsset";
        _key: string;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt: string;
        caption?: string;
        attribution?: string;
      }
    | {
        _type: "splitSection";
        _key: string;
        eyebrow: string | null;
        title: string;
        ctaText: string | null;
        ctaImage: ImageAsset;
        ctaNavigation1: Navigation | null;
        ctaNavigation2: Navigation | null;
        layout: "image-left" | "image-right" | null;
        intent: "dark" | "muted" | "neutral" | "primary" | "white";
      }
    | {
        _type: "testimonialsSection";
        _key: string;
        title?: string;
        subtext?: string;
        testimonialList: Array<{
          rating?: number;
          testimonialText: string;
          name: string;
          occupation?: string;
          location: string;
          _type: "testimonial";
          _key: string;
        }>;
      }
    | {
        _type: "userStorySection";
        _key: string;
        title: string;
        subtext?: string;
        headlineImage: ImageAsset;
        storyBlocks?: Array<
          {
            _key: string;
          } & UserStoryInstance
        >;
      }
  >;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n*[_type == "siteSettings"][0]{\n  "pageSections": landingPage->pageSections[]{\n    _type,\n    _key,\n    _type == "heroSection" => \n{\n      "title": hero->title,\n      "text": hero->heroText,\n      "heroNavigation1": hero->heroNavigation1,\n      "heroNavigation2": hero->heroNavigation2,\n      "muxVideo": hero->muxVideo {\n        "playbackId":asset->playbackId,\n      },\n      "heroImage": hero->heroImage\n    },\n    _type == "splitSection" => {\n      "eyebrow": content->eyebrow,\n      "title": content->title,\n      "ctaText": content->text,\n      "ctaImage": content->ctaImage,\n      "ctaNavigation1": content->ctaNavigation1,\n      "ctaNavigation2": content->ctaNavigation2,\n      layout, \n      intent\n    }, \n_type == "imageAsset" => {\n  ...,\n  image\n},\n  _type == "userStorySection" => {\n    ...\n  }, \n  _type == "carousel" => {\n    ...\n  }, \n  _type == "testimonialsSection" => {\n    ...\n  }, \n  _type == "ctaSection" => {\n    "alignment":contentAlignment.alignmentType,\n    theme,\n    "ctaImage": content -> ctaImage,\n    "ctaNavigation1": content -> ctaNavigation1, \n    "ctaNavigation2": content->ctaNavigation2, \n    "ctaText": content->text, \n    "ctaTitle": content->title,\n  }\n  }\n\n  }\n': LandingPageQueryResult;
    '\n  *[_type == "marketingPage" && slug.current == $slug][0] {\n    "pageSections": pageSections[] \n      {\n    _type,\n    _key,\n    _type == "heroSection" => \n{\n      "title": hero->title,\n      "text": hero->heroText,\n      "heroNavigation1": hero->heroNavigation1,\n      "heroNavigation2": hero->heroNavigation2,\n      "muxVideo": hero->muxVideo {\n        "playbackId":asset->playbackId,\n      },\n      "heroImage": hero->heroImage\n    },\n    _type == "splitSection" => {\n      "eyebrow": content->eyebrow,\n      "title": content->title,\n      "ctaText": content->text,\n      "ctaImage": content->ctaImage,\n      "ctaNavigation1": content->ctaNavigation1,\n      "ctaNavigation2": content->ctaNavigation2,\n      layout, \n      intent\n    }, \n_type == "imageAsset" => {\n  ...,\n  image\n},\n  _type == "userStorySection" => {\n    ...\n  }, \n  _type == "carousel" => {\n    ...\n  }, \n  _type == "testimonialsSection" => {\n    ...\n  }, \n  _type == "ctaSection" => {\n    "alignment":contentAlignment.alignmentType,\n    theme,\n    "ctaImage": content -> ctaImage,\n    "ctaNavigation1": content -> ctaNavigation1, \n    "ctaNavigation2": content->ctaNavigation2, \n    "ctaText": content->text, \n    "ctaTitle": content->title,\n  }\n  }\n\n   }   \n': MarketingPageQueryResult;
  }
}
