/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type Carousel = {
  _id: string;
  _type: "carousel";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: string;
  carouselImages?: Array<
    {
      _key: string;
    } & ImageAsset
  >;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  rating?: number;
  testimonialText?: string;
  name?: string;
  occupation?: string;
  location?: string;
};

export type UserStorySection = {
  _id: string;
  _type: "userStorySection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtext?: string;
  headlineImage?: ImageAsset;
  storyBlocks?: Array<
    {
      _key: string;
    } & UserStoryInstance
  >;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type NavigationHeaderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "navigationHeader";
};

export type FooterReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "footer";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landingPage?: PageReference;
  navbar?: NavigationHeaderReference;
  footer?: FooterReference;
};

export type CompanyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "company";
};

export type NavigationHeader = {
  _id: string;
  _type: "navigationHeader";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: CompanyReference;
  navigationLinks?: Array<
    {
      _key: string;
    } & Navigation
  >;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyDetails?: CompanyReference;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Company = {
  _id: string;
  _type: "company";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  yearEstablished?: string;
  address?: Address;
  phone?: string;
  socialMediaLinks?: Array<
    {
      _key: string;
    } & SocialMedia
  >;
  logos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "logoImage";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Address = {
  _type: "address";
  streetName?: string;
  streetNumber?: string;
  postCode?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageType?: "landing" | "documentation";
  publishedAt?: string;
  updatedAt?: string;
  pageSections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & CtaSection)
    | ({
        _key: string;
      } & SplitSection)
    | {
        title?: string;
        subtext?: string;
        headlineImage?: ImageAsset;
        storyBlocks?: Array<
          {
            _key: string;
          } & UserStoryInstance
        >;
        _type: "userStorySection";
        _key: string;
      }
    | {
        rating?: number;
        testimonialText?: string;
        name?: string;
        occupation?: string;
        location?: string;
        _type: "testimonial";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageAsset)
    | {
        headline?: string;
        carouselImages?: Array<
          {
            _key: string;
          } & ImageAsset
        >;
        _type: "carousel";
        _key: string;
      }
  >;
};

export type ImageAsset = {
  _type: "imageAsset";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  caption?: string;
  attribution?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type CtaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "cta";
};

export type CtaSection = {
  _type: "ctaSection";
  content?: CtaReference;
  contentAlignment?: Alignment;
  backgroundImage?: ImageAsset;
  theme?: "primary" | "background" | "dark";
};

export type Alignment = {
  _type: "alignment";
  alignmentType?: "left" | "right" | "center";
};

export type SplitSection = {
  _type: "splitSection";
  content?: CtaReference;
  layout?: "image-left" | "image-right";
};

export type UserStoryInstance = {
  _type: "userStoryInstance";
  storyText?: string;
  userStoryImage?: ImageAsset;
};

export type Cta = {
  _id: string;
  _type: "cta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  eyebrow?: string;
  text?: string;
  ctaImage?: ImageAsset;
  ctaNavigation1?: Navigation;
  ctaNavigation2?: Navigation;
};

export type Navigation = {
  _type: "navigation";
  title?: string;
  type?: "internal" | "external";
  internalLink?: string;
  link?: string;
};

export type HeroReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "hero";
};

export type HeroSection = {
  _type: "heroSection";
  hero?: HeroReference;
  alignment?: Alignment;
};

export type Hero = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heroText?: string;
  heroImage?: ImageAsset;
  muxVideo?: MuxVideo;
  heroNavigation1?: Navigation;
  heroNavigation2?: Navigation;
};

export type MuxVideoAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mux.videoAsset";
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: MuxVideoAssetReference;
};

export type RichText = {
  _type: "richText";
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SocialMedia = {
  _type: "socialMedia";
  socialMediaTitle?: string;
  socialMediaLink?: string;
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<
    {
      _key: string;
    } & MuxTrack
  >;
  playback_ids?: Array<
    {
      _key: string;
    } & MuxPlaybackId
  >;
  static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<
    {
      _key: string;
    } & MuxStaticRenditionFile
  >;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  name?: string;
  ext?: string;
  height?: number;
  width?: number;
  bitrate?: number;
  filesize?: string;
  type?: string;
  status?: string;
  resolution_tier?: string;
  resolution?: string;
  id?: string;
  passthrough?: string;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
  language_code?: string;
  name?: string;
  status?: string;
  text_source?: string;
  text_type?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Carousel
  | Testimonial
  | UserStorySection
  | PageReference
  | NavigationHeaderReference
  | FooterReference
  | SiteSettings
  | CompanyReference
  | NavigationHeader
  | Footer
  | SanityImageAssetReference
  | Company
  | SanityImageCrop
  | SanityImageHotspot
  | Address
  | Page
  | ImageAsset
  | Slug
  | CtaReference
  | CtaSection
  | Alignment
  | SplitSection
  | UserStoryInstance
  | Cta
  | Navigation
  | HeroReference
  | HeroSection
  | Hero
  | MuxVideoAssetReference
  | MuxVideo
  | RichText
  | SocialMedia
  | MuxVideoAsset
  | MuxAssetData
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: landingPageQuery
// Query: *[_type == "siteSettings"][0]{  landingPage -> {    pageSections  }}
export type LandingPageQueryResult = {
  landingPage: {
    pageSections: Array<
      | ({
          _key: string;
        } & CtaSection)
      | ({
          _key: string;
        } & HeroSection)
      | ({
          _key: string;
        } & ImageAsset)
      | ({
          _key: string;
        } & SplitSection)
      | {
          headline?: string;
          carouselImages?: Array<
            {
              _key: string;
            } & ImageAsset
          >;
          _type: "carousel";
          _key: string;
        }
      | {
          rating?: number;
          testimonialText?: string;
          name?: string;
          occupation?: string;
          location?: string;
          _type: "testimonial";
          _key: string;
        }
      | {
          title?: string;
          subtext?: string;
          headlineImage?: ImageAsset;
          storyBlocks?: Array<
            {
              _key: string;
            } & UserStoryInstance
          >;
          _type: "userStorySection";
          _key: string;
        }
    > | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n  landingPage -> {\n    pageSections\n  }\n}': LandingPageQueryResult;
  }
}
